from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Protocol

from .models import CapabilityReceipt, LifecycleReceipt, ProbeContext


class ExecutionAdapter(Protocol):
    def probe(self, context: ProbeContext) -> CapabilityReceipt: ...

    def prepare(self, contract: Mapping[str, Any]) -> LifecycleReceipt: ...

    def dispatch(self, prepared: Mapping[str, Any]) -> LifecycleReceipt: ...

    def status(self, dispatch_id: str) -> LifecycleReceipt: ...

    def collect(self, dispatch_id: str) -> Mapping[str, Any]: ...

    def cancel(self, dispatch_id: str) -> LifecycleReceipt: ...

    def cleanup(self, dispatch_id: str) -> LifecycleReceipt: ...
