# path: engine/boundary/__init__.py
# filename: __init__.py
# purpose: Public exports for the boundary package
# dependencies/interfaces: Re-exports canonical boundary types and factories

from .command_factory import (
    AdminCommand,
    CommandFactory,
    DEFAULT_COMMAND_FACTORY,
    DelegationRequest,
    EmittedEvent,
    EngineResult,
    ExecutionContext,
    MatchCommand,
    MemoryWriteDirective,
    ReplayCommand,
    SyncCommand,
)
from .delegation_factory import DelegationFactory
from .failure_factory import (
    DEFAULT_FAILURE_FACTORY,
    FailureContext,
    FailureFactory,
    FailurePayload,
    L9BoundaryError,
)
from .ingress_validator import (
    IngressValidationError,
    IngressValidationResult,
    IngressValidator,
)
from .memory_mapper import MemoryLineage, MemoryMapper, MemoryRecord
from .replay_factory import ReplayFactory, ReplayPolicy
from .response_factory import ResponseFactory
from .transport_codec import (
    Classification,
    DelegationLink,
    EncryptionStatus,
    HopEntry,
    HopStatus,
    PacketAddress,
    PacketAttachment,
    PacketGovernance,
    PacketHeader,
    PacketLineage,
    PacketSecurity,
    PacketType,
    TenantContext,
    TransportPacket,
    append_delegation,
    append_hop,
    build_delegation_proof,
    canonical_json,
    compute_content_hash,
    compute_envelope_hash,
    compute_signature,
    decode_packet,
    derive_packet,
    encode_packet,
    packet_size_bytes,
    sha256_hex,
    utc_now,
    verify_signature,
)

__all__ = [
    "AdminCommand",
    "Classification",
    "CommandFactory",
    "DEFAULT_COMMAND_FACTORY",
    "DEFAULT_FAILURE_FACTORY",
    "DelegationFactory",
    "DelegationLink",
    "DelegationRequest",
    "EmittedEvent",
    "EncryptionStatus",
    "EngineResult",
    "ExecutionContext",
    "FailureContext",
    "FailureFactory",
    "FailurePayload",
    "HopEntry",
    "HopStatus",
    "IngressValidationError",
    "IngressValidationResult",
    "IngressValidator",
    "L9BoundaryError",
    "MatchCommand",
    "MemoryLineage",
    "MemoryMapper",
    "MemoryRecord",
    "MemoryWriteDirective",
    "PacketAddress",
    "PacketAttachment",
    "PacketGovernance",
    "PacketHeader",
    "PacketLineage",
    "PacketSecurity",
    "PacketType",
    "ReplayCommand",
    "ReplayFactory",
    "ReplayPolicy",
    "ResponseFactory",
    "SyncCommand",
    "TenantContext",
    "TransportPacket",
    "append_delegation",
    "append_hop",
    "build_delegation_proof",
    "canonical_json",
    "compute_content_hash",
    "compute_envelope_hash",
    "compute_signature",
    "decode_packet",
    "derive_packet",
    "encode_packet",
    "packet_size_bytes",
    "sha256_hex",
    "utc_now",
    "verify_signature",
]
