#!/usr/bin/env python3
"""Generate commands/COMMANDS_MANIFEST.yaml from commands/*.md on disk."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

DEFAULT_EXCLUDED = [
    "commands/README.md",
    "commands/commands-index.md",
    "commands/COMMANDS_MANIFEST.yaml",
    "commands/_harvest-copy-REVIEW.md",
    "commands/_archived/",
    "commands/dora-commands/",
    "commands/emma-repo-commands/",
]


def load_frontmatter(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---\n", 4)
    if end < 0:
        return {}
    data = yaml.safe_load(text[4:end]) or {}
    return data if isinstance(data, dict) else {}


def is_excluded(rel: str, excluded: list[str]) -> bool:
    for pattern in excluded:
        if pattern.endswith("/"):
            if rel.startswith(pattern) or rel.startswith(pattern.rstrip("/") + "/"):
                return True
        elif rel == pattern:
            return True
    return False


def slash_for(path: Path, fm: dict[str, Any], prior: dict[str, Any]) -> str:
    if prior.get("slash"):
        return str(prior["slash"])
    name = str(fm.get("name") or path.stem).strip().lstrip("/")
    return f"/{name}"


def build_manifest(root: Path) -> dict[str, Any]:
    commands_dir = root / "commands"
    existing_path = commands_dir / "COMMANDS_MANIFEST.yaml"
    existing: dict[str, Any] = {}
    if existing_path.is_file():
        loaded = yaml.safe_load(existing_path.read_text(encoding="utf-8")) or {}
        if isinstance(loaded, dict):
            existing = loaded

    excluded = list(existing.get("excluded") or DEFAULT_EXCLUDED)
    prior_by_file = {
        str(entry.get("file")): entry
        for entry in existing.get("commands", []) or []
        if isinstance(entry, dict) and entry.get("file")
    }

    commands: list[dict[str, Any]] = []
    used_slashes: set[str] = set()
    for path in sorted(commands_dir.glob("*.md")):
        rel = f"commands/{path.name}"
        if is_excluded(rel, excluded):
            continue
        fm = load_frontmatter(path)
        prior = prior_by_file.get(rel, {})
        slash = slash_for(path, fm, prior)
        if slash in used_slashes:
            # Collision: fall back to filename stem.
            slash = f"/{path.stem}"
        used_slashes.add(slash)
        entry: dict[str, Any] = {
            "slash": slash,
            "file": rel,
            "enabled": bool(prior.get("enabled", True)),
        }
        aliases = prior.get("aliases")
        if aliases:
            entry["aliases"] = aliases
        commands.append(entry)

    # Preserve stable ordering by slash
    commands.sort(key=lambda item: str(item["slash"]))

    manifest: dict[str, Any] = {
        "version": existing.get("version", 1),
        "updated": existing.get("updated", "auto"),
        "status": existing.get("status", "active"),
        "activation": existing.get(
            "activation",
            {
                "plugin": "l9-governance",
                "plugin_path": "~/.cursor/plugins/local/l9-governance",
                "commands_dir": "commands/",
                "repo_symlink": ".cursor-commands",
            },
        ),
        "resolution_order": existing.get(
            "resolution_order",
            [
                ".cursor/commands/{cmd}.md",
                ".cursor-commands/commands/{cmd}.md",
                "L9 skill (skills/AUTONOMY_MANIFEST.yaml) when file absent",
            ],
        ),
        "commands": commands,
        "excluded": excluded,
    }
    for key in ("purpose", "cursor_discovery"):
        if key in existing:
            manifest[key] = existing[key]
    return manifest


def render(manifest: dict[str, Any]) -> str:
    header = (
        "# L9 Cursor Governance — slash command registry\n"
        "# Generated by ops/scripts/generate_commands_manifest.py — do not hand-edit the\n"
        "# commands: list; re-run the generator (or make pr / sync_generated_artifacts).\n"
        "# Excluded paths and activation metadata are preserved across regenerations.\n"
    )
    body = yaml.safe_dump(manifest, sort_keys=False, allow_unicode=True, width=1000)
    return header + body


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args()
    root = args.root.resolve()
    manifest = build_manifest(root)
    out = root / "commands" / "COMMANDS_MANIFEST.yaml"
    text = render(manifest)
    if out.is_file() and out.read_text(encoding="utf-8") == text:
        print(f"CURRENT: {out.relative_to(root)}")
        return 0
    out.write_text(text, encoding="utf-8")
    print(f"WROTE: {out.relative_to(root)} ({len(manifest['commands'])} commands)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
