#!/usr/bin/env bash
# Install the GOVERNED commit hook: local verification at commit time.
#
# Why this exists, and why `pre-commit install` is still forbidden:
#
#   `pre-commit install` writes a shim that runs the whole catalog with NO
#   SKIP list. On a non-cursor surface `symlinks-check` asserts Cursor desktop
#   wiring the surface is not supposed to have, so every commit is rejected.
#   That is the entire reason this repo ships no commit hook — see
#   ops/scripts/run_pr_precommit.sh and
#   environment/agents/adapters/claude-code/validate_claude_env.py
#   (check_session_deps_installs_no_git_hook).
#
#   The shim installed here does NOT call `pre-commit` directly. It delegates
#   to run_pr_precommit.sh --staged, which resolves the surface-aware SKIP list
#   from one place. Same catalog, same exclusions as `make pr-check`, applied to
#   the index. That removes the reason for the prohibition instead of ignoring
#   it.
#
# This is OPT-IN and machine-local: .git/hooks is not tracked, so nothing here
# changes another clone. It does not replace `make pr-check` / `make pr`, which
# remain the public gate; it closes the window in which a commit is written with
# nothing having verified it.
#
# Usage:
#   bash ops/scripts/install_commit_hook.sh [--force] [--uninstall] [<repo>]
set -euo pipefail

MARKER="L9_GOVERNED_COMMIT_HOOK_V1"
FORCE=0
UNINSTALL=0
ARGS=()
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    --uninstall) UNINSTALL=1 ;;
    *) ARGS+=("$arg") ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
GOV_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
REPO="${ARGS[0]:-$(pwd)}"
REPO="$(cd "$REPO" && git rev-parse --show-toplevel)"

HOOKS_DIR="$(git -C "$REPO" rev-parse --git-path hooks)"
case "$HOOKS_DIR" in
  /*) ;;
  *) HOOKS_DIR="$REPO/$HOOKS_DIR" ;;
esac
SHIM="$HOOKS_DIR/pre-commit"

if [[ "$UNINSTALL" == "1" ]]; then
  if [[ -f "$SHIM" ]] && grep -q "$MARKER" "$SHIM"; then
    rm -f -- "$SHIM"
    echo "REMOVED: $SHIM (was the governed shim)"
    exit 0
  fi
  echo "SKIP: $SHIM is not the governed shim; refusing to remove a hook this script did not write" >&2
  exit 1
fi

# Governance clone only, deliberately. The catalog's local hooks use repo-local
# `entry: ops/scripts/...` paths and several are `pass_filenames: false`, so they
# resolve against the workspace cwd. In a consumer checkout those paths do not
# exist and the hook fails EVERY commit, including a clean one — verified, not
# assumed. run_pr_precommit.sh records the same limit: driving the governance
# config against a consumer workspace needs cwd=$GOV_ROOT plus a governance-only
# skip subset, and that path is not validated. Refusing here is the difference
# between "no commit hook" and "a commit hook that rejects everything".
if [[ "$REPO" != "$GOV_ROOT" && "$FORCE" != "1" ]]; then
  echo "FAIL: $REPO is not the governance clone ($GOV_ROOT)." >&2
  echo "      The hook catalog's local hooks resolve repo-relative entry paths," >&2
  echo "      so in a consumer checkout this shim fails every commit." >&2
  echo "      Consumers verify with \`l9 pr\` / \`make -C \$GOV pr WS=\$PWD\`." >&2
  exit 1
fi

configured="$(git -C "$REPO" config --get core.hooksPath || true)"
if [[ -n "$configured" ]]; then
  echo "NOTE: core.hooksPath is set to '$configured'; installing into $HOOKS_DIR" >&2
fi

if [[ -f "$SHIM" ]] && ! grep -q "$MARKER" "$SHIM" && [[ "$FORCE" != "1" ]]; then
  echo "FAIL: $SHIM exists and was not written by this script." >&2
  echo "      Refusing to overwrite a hook someone else installed. Re-run with --force." >&2
  exit 1
fi

mkdir -p "$HOOKS_DIR"
cat >"$SHIM" <<HOOK
#!/usr/bin/env bash
# $MARKER — generated by ops/scripts/install_commit_hook.sh. Do not hand-edit.
# Runs the governance hook catalog over the index with the surface-aware SKIP
# list. Re-generate by re-running the installer.
set -euo pipefail
exec bash "$GOV_ROOT/ops/scripts/run_pr_precommit.sh" --staged "\$(git rev-parse --show-toplevel)"
HOOK
chmod +x "$SHIM"

echo "INSTALLED: $SHIM"
echo "  catalog:  $GOV_ROOT/.pre-commit-config.yaml"
echo "  runner:   run_pr_precommit.sh --staged (surface-aware SKIP list)"
echo "  verify:   python3 $GOV_ROOT/ops/autonomy/verification_bypass_gate.py --status"
echo "  remove:   bash ops/scripts/install_commit_hook.sh --uninstall"
