"""Structured reason codes the Controller emits on authority decisions (§22).

Every refusal or classification that changes what an operator or the runner
must do next carries one of these as `error_code` (CLI: `error_code` in the
JSON error payload) or in a receipt's `reason_codes`. Logs and status output
make authority decisions visible without becoming a second state store.
"""

from __future__ import annotations

# Program identity / relock (R1, R2)
PROGRAM_LOCK_GLOBAL_DRIFT = "PROGRAM_LOCK_GLOBAL_DRIFT"
RELOCK_SCOPE_INSUFFICIENT = "RELOCK_SCOPE_INSUFFICIENT"
LOCK_INVALID = "LOCK_INVALID"
SCHEMA_INCOMPATIBLE = "SCHEMA_INCOMPATIBLE"
RESUME_SOURCE_MISMATCH = "RESUME_SOURCE_MISMATCH"
RESUME_SOURCE_UNVERIFIED = "RESUME_SOURCE_UNVERIFIED"

# Execution attempts / fencing (R4, R5)
EXECUTION_BASELINE_MISSING = "EXECUTION_BASELINE_MISSING"
EXECUTION_ATTEMPT_STILL_LIVE = "EXECUTION_ATTEMPT_STILL_LIVE"
EXECUTION_FENCE_UNPROVEN = "EXECUTION_FENCE_UNPROVEN"
STALE_LEASE_RESULT = "STALE_LEASE_RESULT"
STALE_ATTEMPT_RESULT = "STALE_ATTEMPT_RESULT"

# Gates (R7)
GATE_EVIDENCE_MISSING = "GATE_EVIDENCE_MISSING"
GATE_EVIDENCE_STALE = "GATE_EVIDENCE_STALE"
GATE_EVIDENCE_CONTRADICTS = "GATE_EVIDENCE_CONTRADICTS"
GATE_EVIDENCE_OUT_OF_SCOPE = "GATE_EVIDENCE_OUT_OF_SCOPE"
GATE_VERIFICATION_REQUIRED = "GATE_VERIFICATION_REQUIRED"
GATE_UNKNOWN_TYPE = "GATE_UNKNOWN_TYPE"
GATE_DEFINITION_INACTIVE = "GATE_DEFINITION_INACTIVE"
GATE_EXPECTATION_MISMATCH = "GATE_EXPECTATION_MISMATCH"
GATE_WAIVER_INVALID = "GATE_WAIVER_INVALID"
GATE_WAIVER_NOT_ALLOWED = "GATE_WAIVER_NOT_ALLOWED"

# Terminal lifecycle (R6)
TERMINAL_BLOCKED = "TERMINAL_BLOCKED"
TERMINAL_BLOCKED_ACTIVE_LEASE = "TERMINAL_BLOCKED_ACTIVE_LEASE"
TERMINAL_BLOCKED_ACTIVE_ATTEMPT = "TERMINAL_BLOCKED_ACTIVE_ATTEMPT"
TERMINAL_ALREADY_CLOSED = "TERMINAL_ALREADY_CLOSED"
TERMINAL_AUTHORITY_MISSING = "TERMINAL_AUTHORITY_MISSING"
TERMINAL_STATE_INCONSISTENT = "TERMINAL_STATE_INCONSISTENT"

# Persistence (R3, R8)
LEDGER_PROJECTION_PENDING = "LEDGER_PROJECTION_PENDING"
RECEIPT_PROJECTION_PENDING = "RECEIPT_PROJECTION_PENDING"
RUNTIME_RECONCILIATION_REQUIRED = "RUNTIME_RECONCILIATION_REQUIRED"
RUNTIME_SCHEMA_INCOMPATIBLE = "RUNTIME_SCHEMA_INCOMPATIBLE"
RUNTIME_WRITER_BUSY = "RUNTIME_WRITER_BUSY"

# Peer Execution (R9)
PROVIDER_FAILOVER_UNSAFE = "PROVIDER_FAILOVER_UNSAFE"
PROVIDER_RETRY_EXHAUSTED = "PROVIDER_RETRY_EXHAUSTED"

# Legacy dispositions (R12)
LEGACY_VERIFIED = "LEGACY_VERIFIED"
LEGACY_UNVERIFIED = "LEGACY_UNVERIFIED"

ALL_REASON_CODES: frozenset[str] = frozenset(
    value for name, value in globals().items() if name.isupper() and isinstance(value, str)
)
